/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "on-background": "#e2e2e2",
              "inverse-surface": "#e2e2e2",
              "primary": "#ffffff",
              "primary-fixed-dim": "#c6c6c6",
              "secondary-container": "#00eefc",
              "surface-container-high": "#282a2b",
              "on-tertiary-container": "#757575",
              "tertiary": "#c6c6c6",
              "on-secondary-fixed": "#002022",
              "on-tertiary": "#303030",
              "surface-container-highest": "#333535",
              "on-tertiary-fixed": "#1b1b1b",
              "on-surface": "#ffffff",
              "on-secondary-container": "#00686f",
              "inverse-on-surface": "#2f3131",
              "on-primary-fixed": "#1b1b1b",
              "surface-variant": "#333535",
              "secondary-fixed-dim": "#00dbe9",
              "on-error-container": "#ffdad6",
              "secondary": "#d3fbff",
              "on-primary-container": "#000000",
              "on-tertiary-fixed-variant": "#474747",
              "surface-tint": "#c6c6c6",
              "tertiary-container": "#000000",
              "on-secondary": "#00363a",
              "surface-container": "#1a1c1c",
              "primary-container": "#ffffff",
              "inverse-primary": "#5e5e5e",
              "outline": "#4c4546",
              "surface-container-low": "#0c0f0f",
              "secondary-fixed": "#7df4ff",
              "on-primary": "#000000",
              "error": "#ffb4ab",
              "surface-dim": "#000000",
              "primary-fixed": "#e2e2e2",
              "tertiary-fixed-dim": "#c6c6c6",
              "error-container": "#93000a",
              "on-primary-fixed-variant": "#474747",
              "background": "#000000",
              "surface-bright": "#37393a",
              "outline-variant": "#333535",
              "on-surface-variant": "#988e90",
              "on-secondary-fixed-variant": "#004f54",
              "on-error": "#690005",
              "surface-container-lowest": "#000000",
              "surface": "#000000",
              "tertiary-fixed": "#e2e2e2"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "container-margin": "24px",
              "gutter": "16px",
              "xl": "40px",
              "sm": "8px",
              "md": "16px",
              "unit": "4px",
              "xs": "4px",
              "lg": "24px"
      },
      "fontFamily": {
              "body-lg": ["Geist", "sans-serif"],
              "body-md": ["Geist", "sans-serif"],
              "headline-md": ["Geist", "sans-serif"],
              "headline-lg": ["Geist", "sans-serif"],
              "display-lg": ["Geist", "sans-serif"],
              "label-sm": ["JetBrains Mono", "monospace"],
              "label-md": ["JetBrains Mono", "monospace"]
      },
      "fontSize": {
              "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
              "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
              "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "label-sm": ["12px", {"lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500"}],
              "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
