"""
Extension-related SQLAlchemy models.
- ExtensionActivationCode: Codes generated by admin that let users activate the extension
- ExtensionDevice: Each installed extension instance (device)
- ExtensionHeartbeat: Hourly ping from each device (for admin reporting)
- ExtensionSubmissionLog: Log of every batch submission from extension devices
- ExtensionDiscoveryEvent: Forensic audit trail for every single recruiter contact discovered/enriched
"""
from sqlalchemy import Column, Integer, String, Boolean, Text, TIMESTAMP, ForeignKey
from sqlalchemy.sql import func
from ..database import Base


class ExtensionActivationCode(Base):
    """One-time or multi-use codes that activate the extension."""
    __tablename__ = "extension_activation_codes"

    id = Column(Integer, primary_key=True, index=True)
    code = Column(String(64), unique=True, index=True, nullable=False)
    # The owner who generated this code (admin user)
    owner_user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    label = Column(String(200), nullable=True)  # e.g. "Shared with John's team"
    max_uses = Column(Integer, default=1)  # -1 = unlimited
    use_count = Column(Integer, default=0)
    is_active = Column(Boolean, default=True)
    expires_at = Column(TIMESTAMP, nullable=True)
    created_at = Column(TIMESTAMP, server_default=func.now())


class ExtensionDevice(Base):
    """Each unique extension installation (device)."""
    __tablename__ = "extension_devices"

    id = Column(Integer, primary_key=True, index=True)
    device_id = Column(String(64), unique=True, index=True, nullable=False)  # crypto.randomUUID()
    activation_code_id = Column(Integer, ForeignKey("extension_activation_codes.id", ondelete="SET NULL"), nullable=True)
    owner_user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    extension_version = Column(String(20), nullable=True)
    user_agent = Column(String(300), nullable=True)
    first_seen_at = Column(TIMESTAMP, server_default=func.now())
    last_seen_at = Column(TIMESTAMP, server_default=func.now(), onupdate=func.now())
    # Running totals
    total_submitted = Column(Integer, default=0)
    total_accepted = Column(Integer, default=0)
    total_duplicates = Column(Integer, default=0)
    is_active = Column(Boolean, default=True)


class ExtensionHeartbeat(Base):
    """Hourly status ping from each extension device."""
    __tablename__ = "extension_heartbeats"

    id = Column(Integer, primary_key=True, index=True)
    device_id = Column(String(64), index=True, nullable=False)
    owner_user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    session_captured = Column(Integer, default=0)
    session_sent = Column(Integer, default=0)
    session_duplicates = Column(Integer, default=0)
    queue_pending = Column(Integer, default=0)
    total_ever_sent = Column(Integer, default=0)
    extension_version = Column(String(20), nullable=True)
    reported_at = Column(TIMESTAMP, server_default=func.now(), index=True)


class ExtensionSubmissionLog(Base):
    """Log of every batch received from an extension device."""
    __tablename__ = "extension_submission_logs"

    id = Column(Integer, primary_key=True, index=True)
    device_id = Column(String(64), index=True, nullable=False)
    owner_user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    contacts_received = Column(Integer, default=0)
    contacts_accepted = Column(Integer, default=0)
    contacts_duplicate = Column(Integer, default=0)
    contacts_errored = Column(Integer, default=0)
    source_sites = Column(Text, nullable=True)  # JSON array of domains scraped
    submitted_at = Column(TIMESTAMP, server_default=func.now(), index=True)


class ExtensionDiscoveryEvent(Base):
    """Forensic provenance log for every candidate contact discovered or enriched by the extension."""
    __tablename__ = "extension_discovery_events"

    id = Column(Integer, primary_key=True, index=True)
    discovery_id = Column(String(64), unique=True, index=True, nullable=False)  # e.g. DISC-8F21A91
    capture_id = Column(String(64), index=True, nullable=True)  # e.g. VC-00192
    device_id = Column(String(64), index=True, nullable=False)
    owner_user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    recruiter_id = Column(Integer, ForeignKey("recruiters.recruiter_id", ondelete="SET NULL"), nullable=True, index=True)
    recruiter_name = Column(String(150), nullable=False)
    company_name = Column(String(255), nullable=True)
    title = Column(String(150), nullable=True)
    email = Column(String(150), nullable=True)
    phone = Column(String(50), nullable=True)
    linkedin_url = Column(String(255), nullable=True)
    location = Column(String(255), nullable=True)
    source_url = Column(String(500), nullable=True)
    source_page_title = Column(String(255), nullable=True)
    extraction_source = Column(String(50), default="visual_dom_fusion")  # visual_capture, dom, fusion
    visual_change_score = Column(String(20), nullable=True)
    confidence = Column(Integer, default=90)
    db_action = Column(String(30), default="NEW_DISCOVERY")  # NEW_DISCOVERY, ENRICHED, PREVIOUSLY_KNOWN
    fields_added = Column(Text, nullable=True)  # JSON list of fields added
    created_at = Column(TIMESTAMP, server_default=func.now(), index=True)
