"""add_trusted_devices_columns

Revision ID: 2db322e23cde
Revises: fd9fa10852f3
Create Date: 2026-07-29 23:36:53.299554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2db322e23cde'
down_revision: Union[str, Sequence[str], None] = 'fd9fa10852f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auto_approve_cidrs', sa.Text(), nullable=True),
    sa.Column('always_require_admin_approval', sa.Boolean(), nullable=True),
    sa.Column('allowed_countries', sa.Text(), nullable=True),
    sa.Column('block_outside_geos', sa.Boolean(), nullable=True),
    sa.Column('max_devices_per_user', sa.Integer(), nullable=True),
    sa.Column('default_trust_duration_days', sa.Integer(), nullable=True),
    sa.Column('idle_revoke_days', sa.Integer(), nullable=True),
    sa.Column('notify_admins_pending', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_policies_id'), 'device_policies', ['id'], unique=False)
    op.create_table('sentinel_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('total_profiles', sa.Integer(), nullable=True),
    sa.Column('profiles_analyzed', sa.Integer(), nullable=True),
    sa.Column('profiles_repaired', sa.Integer(), nullable=True),
    sa.Column('current_task_description', sa.String(length=255), nullable=True),
    sa.Column('last_processed_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentinel_state_id'), 'sentinel_state', ['id'], unique=False)
    op.create_table('sentinel_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.Column('field_changed', sa.String(length=100), nullable=False),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiters.recruiter_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentinel_audit_logs_id'), 'sentinel_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_sentinel_audit_logs_recruiter_id'), 'sentinel_audit_logs', ['recruiter_id'], unique=False)
    op.create_index(op.f('ix_sentinel_audit_logs_timestamp'), 'sentinel_audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_login_history_ip_address'), 'login_history', ['ip_address'], unique=False)
    op.create_index(op.f('ix_login_history_user_id'), 'login_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_page_visits_session_id'), 'page_visits', ['session_id'], unique=False)
    op.create_index(op.f('ix_page_visits_user_email'), 'page_visits', ['user_email'], unique=False)
    op.create_index(op.f('ix_recruiters_quality_score'), 'recruiters', ['quality_score'], unique=False)
    op.create_index(op.f('ix_recruiters_sentinel_status'), 'recruiters', ['sentinel_status'], unique=False)
    op.add_column('trusted_devices', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('trusted_devices', sa.Column('requires_reverification', sa.Boolean(), nullable=True))
    op.add_column('trusted_devices', sa.Column('risk_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trusted_devices', 'risk_score')
    op.drop_column('trusted_devices', 'requires_reverification')
    op.drop_column('trusted_devices', 'expires_at')
    op.drop_index(op.f('ix_recruiters_sentinel_status'), table_name='recruiters')
    op.drop_index(op.f('ix_recruiters_quality_score'), table_name='recruiters')
    op.drop_index(op.f('ix_page_visits_user_email'), table_name='page_visits')
    op.drop_index(op.f('ix_page_visits_session_id'), table_name='page_visits')
    op.drop_index(op.f('ix_login_history_user_id'), table_name='login_history')
    op.drop_index(op.f('ix_login_history_ip_address'), table_name='login_history')
    op.drop_index(op.f('ix_sentinel_audit_logs_timestamp'), table_name='sentinel_audit_logs')
    op.drop_index(op.f('ix_sentinel_audit_logs_recruiter_id'), table_name='sentinel_audit_logs')
    op.drop_index(op.f('ix_sentinel_audit_logs_id'), table_name='sentinel_audit_logs')
    op.drop_table('sentinel_audit_logs')
    op.drop_index(op.f('ix_sentinel_state_id'), table_name='sentinel_state')
    op.drop_table('sentinel_state')
    op.drop_index(op.f('ix_device_policies_id'), table_name='device_policies')
    op.drop_table('device_policies')
    # ### end Alembic commands ###
