"""add mailintel tracking columns and domain_reputation

Revision ID: f2d95dfa5fd1
Revises: 2db322e23cde
Create Date: 2026-08-03 21:26:39.807030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2d95dfa5fd1'
down_revision: Union[str, Sequence[str], None] = '2db322e23cde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_reputation',
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('total_sent', sa.Integer(), nullable=True),
    sa.Column('total_delivered', sa.Integer(), nullable=True),
    sa.Column('total_bounced', sa.Integer(), nullable=True),
    sa.Column('total_replied', sa.Integer(), nullable=True),
    sa.Column('reputation_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('domain')
    )
    op.create_index(op.f('ix_domain_reputation_domain'), 'domain_reputation', ['domain'], unique=False)
    op.add_column('recruiter_emails', sa.Column('last_campaign_id', sa.Integer(), nullable=True))
    op.add_column('recruiter_emails', sa.Column('last_delivery_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('recruiter_emails', sa.Column('last_reply_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('recruiter_emails', sa.Column('last_bounce_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('recruiter_emails', sa.Column('hard_bounce_count', sa.Integer(), nullable=True))
    op.add_column('recruiter_emails', sa.Column('soft_bounce_count', sa.Integer(), nullable=True))
    op.add_column('recruiter_emails', sa.Column('flag_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_recruiters_user_id'), 'recruiters', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recruiters_user_id'), table_name='recruiters')
    op.drop_column('recruiter_emails', 'flag_reason')
    op.drop_column('recruiter_emails', 'soft_bounce_count')
    op.drop_column('recruiter_emails', 'hard_bounce_count')
    op.drop_column('recruiter_emails', 'last_bounce_at')
    op.drop_column('recruiter_emails', 'last_reply_at')
    op.drop_column('recruiter_emails', 'last_delivery_at')
    op.drop_column('recruiter_emails', 'last_campaign_id')
    op.drop_index(op.f('ix_domain_reputation_domain'), table_name='domain_reputation')
    op.drop_table('domain_reputation')
    # ### end Alembic commands ###
