"""Initial migration

Revision ID: fd9fa10852f3
Revises: 
Create Date: 2026-07-22 19:36:38.223256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd9fa10852f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_aliases')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_table('email_candidates')
    op.drop_index(op.f('ix_campaign_drafts_user_email'), table_name='campaign_drafts')
    op.create_index(op.f('ix_campaign_drafts_user_id'), 'campaign_drafts', ['user_id'], unique=False)
    op.drop_column('campaign_drafts', 'user_email')
    op.alter_column('campaign_recruiters', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('campaign_recruiters', 'max_retries',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.create_index(op.f('ix_campaign_recruiters_queue_position'), 'campaign_recruiters', ['queue_position'], unique=False)
    op.create_index(op.f('ix_campaigns_is_test'), 'campaigns', ['is_test'], unique=False)
    op.drop_index(op.f('idx_companies_location'), table_name='companies')
    op.drop_index(op.f('idx_companies_trgm_name'), table_name='companies', postgresql_using='gin')
    op.create_index(op.f('ix_companies_company_id'), 'companies', ['company_id'], unique=False)
    op.create_index(op.f('ix_companies_is_tracked'), 'companies', ['is_tracked'], unique=False)
    op.alter_column('company_email_patterns', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('company_email_patterns', 'pattern',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.create_index(op.f('ix_company_email_patterns_company_id'), 'company_email_patterns', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_email_patterns_domain'), 'company_email_patterns', ['domain'], unique=False)
    op.create_index(op.f('ix_company_email_patterns_id'), 'company_email_patterns', ['id'], unique=False)
    op.drop_column('company_email_patterns', 'confidence')
    op.drop_column('company_email_patterns', 'source')
    op.alter_column('email_signatures', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_email_signatures_is_default'), 'email_signatures', ['is_default'], unique=False)
    op.create_index(op.f('ix_email_signatures_signature_id'), 'email_signatures', ['signature_id'], unique=False)
    op.create_index(op.f('ix_email_signatures_user_id'), 'email_signatures', ['user_id'], unique=False)
    op.drop_column('email_signatures', 'user_email')
    op.create_index(op.f('ix_email_templates_user_id'), 'email_templates', ['user_id'], unique=False)
    op.drop_index(op.f('uq_enrichment_audit_run'), table_name='enrichment_audit')
    op.drop_constraint(op.f('enrichment_proposals_run_id_recruiter_id_enrichment_type_pr_key'), 'enrichment_proposals', type_='unique')
    op.drop_index(op.f('ix_enrichment_proposals_run_recruiter_type'), table_name='enrichment_proposals')
    op.create_index(op.f('ix_enrichment_proposals_id'), 'enrichment_proposals', ['id'], unique=False)
    op.drop_constraint(op.f('enrichment_results_run_id_recruiter_id_key'), 'enrichment_results', type_='unique')
    op.drop_index(op.f('ix_enrichment_results_run_recruiter'), table_name='enrichment_results')
    op.create_index(op.f('ix_enrichment_results_id'), 'enrichment_results', ['id'], unique=False)
    op.drop_index(op.f('idx_page_visits_visited_at'), table_name='page_visits')
    op.drop_index(op.f('idx_recruiters_location'), table_name='recruiters')
    op.drop_index(op.f('idx_recruiters_specialization'), table_name='recruiters')
    op.drop_index(op.f('idx_recruiters_trgm_name'), table_name='recruiters', postgresql_using='gin')
    op.drop_index(op.f('idx_recruiters_trgm_spec'), table_name='recruiters', postgresql_using='gin')
    op.create_index(op.f('ix_recruiters_recruiter_id'), 'recruiters', ['recruiter_id'], unique=False)
    op.drop_constraint(op.f('recruiters_email_pattern_id_fkey'), 'recruiters', type_='foreignkey')
    op.create_index(op.f('ix_smart_import_jobs_user_id'), 'smart_import_jobs', ['user_id'], unique=False)
    op.create_index(op.f('ix_upload_jobs_user_id'), 'upload_jobs', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_provider_id'), 'users', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_provider_id'), table_name='users')
    op.drop_index(op.f('ix_upload_jobs_user_id'), table_name='upload_jobs')
    op.drop_index(op.f('ix_smart_import_jobs_user_id'), table_name='smart_import_jobs')
    op.create_foreign_key(op.f('recruiters_email_pattern_id_fkey'), 'recruiters', 'company_email_patterns', ['email_pattern_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_recruiters_recruiter_id'), table_name='recruiters')
    op.create_index(op.f('idx_recruiters_trgm_spec'), 'recruiters', ['specialization'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_recruiters_trgm_name'), 'recruiters', ['recruiter_name'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_recruiters_specialization'), 'recruiters', ['specialization'], unique=False)
    op.create_index(op.f('idx_recruiters_location'), 'recruiters', ['location'], unique=False)
    op.create_index(op.f('idx_page_visits_visited_at'), 'page_visits', [sa.literal_column('visited_at DESC')], unique=False)
    op.drop_index(op.f('ix_enrichment_results_id'), table_name='enrichment_results')
    op.create_index(op.f('ix_enrichment_results_run_recruiter'), 'enrichment_results', ['run_id', 'recruiter_id'], unique=False)
    op.create_unique_constraint(op.f('enrichment_results_run_id_recruiter_id_key'), 'enrichment_results', ['run_id', 'recruiter_id'])
    op.drop_index(op.f('ix_enrichment_proposals_id'), table_name='enrichment_proposals')
    op.create_index(op.f('ix_enrichment_proposals_run_recruiter_type'), 'enrichment_proposals', ['run_id', 'recruiter_id', 'enrichment_type'], unique=False)
    op.create_unique_constraint(op.f('enrichment_proposals_run_id_recruiter_id_enrichment_type_pr_key'), 'enrichment_proposals', ['run_id', 'recruiter_id', 'enrichment_type', 'proposed_value'])
    op.create_index(op.f('uq_enrichment_audit_run'), 'enrichment_audit', ['run_id', 'recruiter_id', 'enrichment_type', 'final_value'], unique=True)
    op.drop_index(op.f('ix_email_templates_user_id'), table_name='email_templates')
    op.add_column('email_signatures', sa.Column('user_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_email_signatures_user_id'), table_name='email_signatures')
    op.drop_index(op.f('ix_email_signatures_signature_id'), table_name='email_signatures')
    op.drop_index(op.f('ix_email_signatures_is_default'), table_name='email_signatures')
    op.alter_column('email_signatures', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('company_email_patterns', sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('company_email_patterns', sa.Column('confidence', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_company_email_patterns_id'), table_name='company_email_patterns')
    op.drop_index(op.f('ix_company_email_patterns_domain'), table_name='company_email_patterns')
    op.drop_index(op.f('ix_company_email_patterns_company_id'), table_name='company_email_patterns')
    op.alter_column('company_email_patterns', 'pattern',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('company_email_patterns', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_companies_is_tracked'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_id'), table_name='companies')
    op.create_index(op.f('idx_companies_trgm_name'), 'companies', ['company_name'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_companies_location'), 'companies', ['location'], unique=False)
    op.drop_index(op.f('ix_campaigns_is_test'), table_name='campaigns')
    op.drop_index(op.f('ix_campaign_recruiters_queue_position'), table_name='campaign_recruiters')
    op.alter_column('campaign_recruiters', 'max_retries',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('campaign_recruiters', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('campaign_drafts', sa.Column('user_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_campaign_drafts_user_id'), table_name='campaign_drafts')
    op.create_index(op.f('ix_campaign_drafts_user_email'), 'campaign_drafts', ['user_email'], unique=False)
    op.create_table('email_candidates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recruiter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('candidate_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('domain', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('pattern', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'generated'::character varying"), autoincrement=False, nullable=True),
    sa.Column('evidence', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiters.recruiter_id'], name=op.f('email_candidates_recruiter_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('email_candidates_pkey'))
    )
    op.create_table('system_settings',
    sa.Column('key', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('system_settings_pkey'))
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=False)
    op.create_table('company_aliases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('canonical_company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alias_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('alias_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['canonical_company_id'], ['companies.company_id'], name=op.f('company_aliases_canonical_company_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('company_aliases_pkey'))
    )
    # ### end Alembic commands ###
